Fix Docker context removal step syntax

diff --git a/build-registry/action.yaml b/build-registry/action.yaml
--- a/build-registry/action.yaml
+++ b/build-registry/action.yaml
@@ -82,5 +82,6 @@ runs:
         MSG_MINIMAL: "actions url"
 
     - name: Remove Docker Context (Cleanup)
-        if: always()
-        run: docker context rm buildx-context || echo 'buildx-context not found'
+      if: always()
+      shell: bash
+      run: docker context rm buildx-context || echo 'buildx-context not found'
